<?php
/**
 * @file
 * Consume Aegaron's SOAP Web Service from the Digital Library
 */

/**
 * Implements hook_menu().
 */
function aegaron_soap_menu() {
  $items['search/terms/json'] = array(
    'access callback'   => true, // available to all
    'page callback'     => 'aegaron_soap_search_terms_json_object',
    'delivery callback' => 'drupal_json_output' 
  );

  $items['drawings/json'] = array(
    'access callback'   => true, // available to all
    'page callback'     => 'aegaron_soap__json_object',
    'delivery callback' => 'drupal_json_output' 
  );

  return $items;
}

/**
 * Implements hook_default_wsclient_service().
 */
function aegaron_soap_default_wsclient_service() {
}

/**
 * Implementation of hook_views_query_alter
 * @param type $view
 * @param type $query 
 */
function aegaron_soap_views_query_alter(&$view, &$query) {
}

/**
 * Implementation of hook_theme().
 */
function aegaron_soap_theme($existing, $type, $theme, $path) {

  $themes['views_view__browse_terms__page'] = array(
    'template' => 'views-view--browse-terms--page',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__browse_terms__page_1'] = array(
    'template' => 'views-view--browse-terms--page-1',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__browse_terms__page_2'] = array(
    'template' => 'views-view--browse-terms--page-2',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__browse_terms__page_3'] = array(
    'template' => 'views-view--browse-terms--page-3',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__browse_terms__page_4'] = array(
    'template' => 'views-view--browse-terms--page-4',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
      'aegaron_soap_preprocess_views_view__browse_terms__page_4',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__browse_terms__block_1'] = array(
    'template' => 'views-view--browse-terms--block-1',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__display_term__page'] = array(
    'template' => 'views-view--display-term--page',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__search_terms__page'] = array(
    'template' => 'views-view--search-terms--page',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
      'aegaron_soap_preprocess_views_view__search_terms__page',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__browse_drawings__block'] = array(
    'template' => 'views-view--browse-drawings--block',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__browse_drawings__block_1'] = array(
    'template' => 'views-view--browse-drawings--block-1',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__search_drawings__block'] = array(
    'template' => 'views-view--search-drawings--block',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__search_drawings__page'] = array(
    'template' => 'views-view--search-drawings--page',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  $themes['views_view__detail_drawing__page'] = array(
    'template' => 'views-view--detail-drawing--page',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );

  return $themes;
}

function aegaron_soap_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    if ($form['#id'] == 'views-exposed-form-search-terms-page') {
      $form['tid']['#attributes']['class'] = array('auto_submit');
      drupal_add_js(drupal_get_path('module','aegaron_soap') . '/aegaron_soap_autocomplete.js', array('group' => JS_THEME));
      $form['submit']['#value'] = 'Search';
      //$form['submit']['#type'] = 'image';
      //$form['submit']['#alt'] = 'Search';
      //$form['submit']['#src'] = drupal_get_path('theme','aegaron') . "/assets/img/magglass.png";
// kpr($form);
    }
    if ($form['#id'] == 'views-exposed-form-search-drawings-page') {
      $form['submit']['#value'] = 'Search';
      $form['listall']['#markup'] = '<span class="listall"><a href="/search/plans">Show All Drawings</a></span>';
    }
  }
}

function aegaron_soap_preprocess_views_view__browse_terms__page_4() {

   $flushquery = db_query('SELECT t.tid FROM {taxonomy_term_data} t WHERE t.vid = 2')->fetchCol();
    foreach ($flushquery as $tid) {
      taxonomy_term_delete($tid);
    }

  $service = wsclient_service_load('dev_aegaron_soap_service');
  $result = $service->listAllTerms();
  $xml = new SimpleXMLElement($result->return);

  $terms = array();
  $addterm = new stdClass();

  foreach ($xml->term as $j => $item) {
    foreach ($item->title as $term) {
      if (is_null(existsInArray((string)$term,$terms))) {
        $attr = 'lang';
        $lang = (string)$term->attributes()->$attr;
        array_push($terms, array(
          'name' => (string)$term,
          'field_lang' => $lang,
        ));
        $addterm->tid = '';
        $addterm->vid = 2;
        $addterm->name = (string)$term;
        $addterm->parent = 0;
        $addterm->field_lang[LANGUAGE_NONE][0]['value'] = $lang;
        $test = taxonomy_term_save($addterm);
// kpr($addterm);
      }
    }

    foreach ($item->alttitle as $term) {
      if (is_null(existsInArray((string)$term,$terms))) {
        $attr = 'lang';
        $lang = (string)$term->attributes()->$attr;
        array_push($terms, array(
          'name' => (string)$term,
          'field_lang' => $lang,
        ));
        $addterm->tid = '';
        $addterm->vid = 2;
        $addterm->name = (string)$term;
        $addterm->parent = 0;
        $addterm->field_lang[LANGUAGE_NONE][0]['value'] = $lang;
        $test = taxonomy_term_save($addterm);
// kpr($addterm);
      }
    }
  }
}

function aegaron_soap_preprocess_views_view__search_terms__page() {
}

function aegaron_soap_search_terms_json_object() {
  $terms = array();
  $i = 0;
  $vocab = db_query("SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 2 ORDER BY name asc");
  if ($vocab) {
    while ($row = $vocab->fetchAssoc()) {
      $terms[$i]['tid'] = $row['tid'];
      $terms[$i]['name'] = $row['name'];
      $i++;
    }
    $json_terms = drupal_json_output($terms);
    return $json_terms;
  }
}

function aegaron_soap_plantitle_json_object() {

  $cache_id = 'drawingsjson';
  $cached = cache_get($cache_id, 'cache');
  $drawings = $cached->data;
  if (empty($drawings)) {
    $drawings = array();
    $i = 0;
    $service = wsclient_service_load('dev_aegaron_soap_service');
    $result = $service->listAllDrawings();

    foreach ($result->return as $j => $item) {
      $drawings[$i]['drawing'] = $item->drawing;
      $drawings[$i]['place'] = $item->place;
      $drawings[$i]['planTitle'] = $item->planTitle;
      $i++;
    }

  }
  cache_set($cache_id, $drawings, 'cache', CACHE_TEMPORARY);
  $json_map = drupal_json_output($drawings);
  return $json_map;
}

function existsInArray($str, $array) {
  foreach ($array as $key => $val) {
    if ($val['name'] === $str) {
      return $key;
    }
  }
  return null;
}

