<?php
/**
 * @file
 * Consume Aegaron's SOAP Web Service from the Digital Library
 */

/**
 * Implements hook_default_wsclient_service().
 */
function aegaron_soap_default_wsclient_service() {
}

/**
 * Implementation of hook_views_query_alter
 * @param type $view
 * @param type $query 
 */
function aegaron_soap_views_query_alter(&$view, &$query) {
}

/**
 * Implementation of hook_theme().
 */
function aegaron_soap_theme($existing, $type, $theme, $path) {

  $themes['views_view__browse_terms__page'] = array(
    'template' => 'views-view--browse-terms--page',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );
  $themes['views_view__browse_terms__page_1'] = array(
    'template' => 'views-view--browse-terms--page-1',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );
  $themes['views_view__browse_terms__page_2'] = array(
    'template' => 'views-view--browse-terms--page-2',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );
  $themes['views_view__browse_terms__page_3'] = array(
    'template' => 'views-view--browse-terms--page-3',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );
  $themes['views_view__browse_terms__block_1'] = array(
    'template' => 'views-view--browse-terms--block-1',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );
  $themes['views_view__display_term__page'] = array(
    'template' => 'views-view--display-term--page',
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
    ),
    'arguments' => array('view' => NULL),
    'path' => drupal_get_path('module', 'aegaron_soap'),
  );
  return $themes;
}
