<?php

/**
 * @file
 * The map viewer shows a multi-map display in a block.
 */

/**
 * Implements hook_help().
 */
function map_viewer_help($path, $arg) {
  switch ($path) {
    case 'admin/help#map_viewer':
      return t('<p>The map viewer creates a multi-map display that can be inserted into a block.</p>');
      break;
  }
}

/**
 * Implements hook_js_alter().
 */
function map_viewer_js_alter(&$javascript) {
  // Swap out jQuery to use 1.11.3
  // The map viewer pages require newer jQuery
  // The pages with accordion effects require newer jQuery
  // The CKEditor breaks with newer jQuery
  // TODO - make local
  // path: /drawing*
  // path: /browse*
  // path: /browse/plans
  if (arg(0) == 'drawing' || arg(0) == 'browse' || (arg(0) == 'node' && arg(1) == '1')) {
    // http://code.jquery.com/jquery-1.11.3.min.js
    $newjquery = drupal_get_path('module','map_viewer') . '/jquery-1.11.3.min.js';
    $javascript['misc/jquery.js'] = drupal_js_defaults($newjquery);
    // $javascript['misc/jquery.js']['data'] = drupal_get_path('module','map_viewer') . '/jquery-1.11.3.min.js';
    $javascript['misc/jquery.js']['group'] = JS_LIBRARY;
    $javascript['misc/jquery.js']['version'] = '1.11.3';
    $javascript['misc/jquery.js']['weight'] = -20;
  }
}

/**
 * Implements hook_library_alter().
 */

/****
 * just not doing the job :(


function map_viewer_library_alter(&$javascript, $module) {
  // Update jQuery to 1.11.3.

kpr($javascript);

  if ($module == 'system' && isset($javascript['jquery'])) {
    // Verify existing version is older than the one we are updating to.
    if (version_compare($javascript['jquery']['version'], '1.11.3', '<')) {
      // Update the existing jQuery to 1.11.3.
      $javascript['jquery']['version'] = '1.11.3';
      $javascript['jquery']['js']['misc/jquery.js'] = array(
        'type' => 'external', 
        'group' => JS_LIBRARY,
        'every_page' => FALSE,
        'weight' => -20,
        'requires_jquery' => FALSE,
        'scope' => 'header',
        'cache' => FALSE,
        'defer' => FALSE,
        'preprocess' => FALSE,
        'version' => NULL, 
        'external' => 'http://code.jquery.com/jquery-1.11.3.min.js', 
      );
      $javascript['drupal.ajax']['js'][] = array(
        'data' => array('ajaxPageState' => array('jquery_version' => '1.11.3')),
        'type' => 'setting',
      );
kpr($javascript);
    }
  }
}
 */

/**
 * Implements hook_block_info().
 */
function map_viewer_block_info() {
  $blocks['map_viewer'] = array(
    'info' => t('Map Viewer'),
    // Drupal default: DRUPAL_CACHE_PER_ROLE
    // TODO - try with various caching options
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function map_viewer_block_view($delta = '') {
  switch ($delta) {
    case 'map_viewer':
      $block['subject'] = t('Map Viewer');
      if (user_access('access content')) {
        $block['content'] = map_viewer_contents();
      }
      break;
  }
  return $block;
}

/**
 * Pulling in js and css.
 */
function map_viewer_files() {

  // jquery
  // TODO - what is this for?
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/jquery-migrate-1.2.1.min.js');

  // bootstrap
  // TODO - make local 
  drupal_add_css('http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css', 'external');

  // bootstrap toggle
  // TODO - make css local 
  drupal_add_css('https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css','external');
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/bootstrap-toggle.min.js');

  // map_viewer css
  drupal_add_css(drupal_get_path('module', 'map_viewer') . '/map_viewer.css');
  drupal_add_css(drupal_get_path('module', 'map_viewer') . '/dd.css');

  // open layers
  // https://cdnjs.cloudflare.com/ajax/libs/ol3/3.4.0/ol.js
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/ol.js');

  // map_viewer js files
  // moved links to html.tpl.php in theme to force load after blocks.js
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/jquery.dd.min.js');
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/map_viewer.aegaron-namespace.js');
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/map_viewer.aegaron-drawings.js');
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/map_viewer.header.js');
  drupal_add_js(drupal_get_path('module', 'map_viewer') . '/map_viewer.metadata.js');
}

/**
 * Custom content function.
 *
 * Pulls all local and external css and js.
 * Sets maps 1, 2, and 3, drop-downs and controls for page.
 * Pulls data from soap service.
 *
 * @return
 *   A multi-map display.
 */
function map_viewer_contents(){
  map_viewer_files();
  $str = file_get_contents(drupal_get_path('module', 'map_viewer') . '/map_viewer.body.inc');
  $mycontent = array('#markup' => $str,);
  return $mycontent;
}


